### ISSUE TITLE
I'm not a coder, but I ran the code well, but now have a problem

### ISSUE THREAD

**Issue by samchen19950130** [Camillerkt/Multiple-Images-Watermark-Remover#1]
When I run this code, it always runs 3-4 images smoothly and then it quits automatically. Every time it exits, the code's prompt is always timeout 30000ms.
`TimeoutError: waiting for selector `.hyUBYz` failed: timeout 30000ms exceeded
    at new WaitTask (/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:680:34)
    at DOMWorld._waitForSelectorInPage (/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:564:26)
    at Object.internalHandler.waitFor (/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:34:29)
    at DOMWorld.waitForSelector (/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:493:29)
    at Frame.waitForSelector (/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:1019:51)
    at Page.waitForSelector (/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2265:33)
    at /Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/index.js:43:16
`

What data do I need to change to avoid this problem?

**Comment by Camillerkt** [comment]
Hello @samchen19950130, the program works with the 2captcha API so you need to create a developer account on 2captcha.com to get your access token.
It's a very cheap service (only 3 USD can be enough).
I invite you to read my documentation to better implement the project: https://github.com/Camillerkt/Multiple-Images-Watermark-Remover

**Comment by samchen19950130** [comment]
> 
Hi Camillerkt,

yes, I've already used 2captcha's token...  But the processing of the images is still interrupted. Now the situation is a little better, after about 5-10 images it stops working.

You can find my feedback from 10 minutes ago here：

PuppeteerExtraPluginRecaptcha: An error occured during "getRecaptchaSolutions": {
  _vendor: 'recaptcha',
  provider: '2captcha',
  id: 'j7gb8ezkc1',
  requestAt: 2022-07-07T00:24:11.049Z,
  error: 'Error: 2captcha error: Error: read ECONNRESET'
}
/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:680
            const timeoutError = new Errors_js_1.TimeoutError(`waiting for ${options.title} failed: timeout ${options.timeout}ms exceeded`);
                                 ^
```

TimeoutError: waiting for selector `.hyUBYz` failed: timeout 30000ms exceeded
    at new WaitTask (/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:680:34)
    at DOMWorld._waitForSelectorInPage (/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:564:26)
    at Object.internalHandler.waitFor (/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:34:29)
    at DOMWorld.waitForSelector (/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:493:29)
    at Frame.waitForSelector (/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:1019:51)
    at Page.waitForSelector (/Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2265:33)
    at /Users/sam1995/Downloads/Multiple-Images-Watermark-Remover-master/index.js:43:16
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by samchen19950130** [comment]
btw, if I change the weibsie from https://www.watermarkremover.io/upload to https://www.erase.bg/upload, is it still work? erase is a background remover tools from same company

**Comment by Camillerkt** [comment]
Hi @samchen19950130,
Apparently the problem is with 2captcha. You seem to have the same problem: https://github.com/berstend/puppeteer-extra/issues/452

If this doesn't solve your problem, make sure your headless value is set to false. Then check that the program comes back to the top of the page once the image download is complete.
Then, on line 39 of the original index.js code, increase the value of sleep(). For example: await sleep(5000).
This might slow down your program but try to see if it solves the problem.
Normally this should solve your problem.

If you want the program to work with erase.bg, you need to modify the code by replacing the address on line 27 with https://www.erase.bg/upload and replacing the selectors on lines 43 and 44 with .xNWSV

Have a nice day.
